namespace Purchasing_Order
{
    partial class Add_Member_Associate
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        [System.Obsolete]
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Add_Member_Associate));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.bunifuPanel3 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtnic = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_member = new Bunifu.UI.WinForms.BunifuTextBox();
            this.guna2ControlBox2 = new Guna.UI2.WinForms.Guna2ControlBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_address = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_cn = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_ma = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.guna2ControlBox1 = new Guna.UI2.WinForms.Guna2ControlBox();
            this.btn_clear = new Guna.UI2.WinForms.Guna2Button();
            this.label7 = new System.Windows.Forms.Label();
            this.txt_sr = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_memberid = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_delete = new Guna.UI2.WinForms.Guna2Button();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btn_update = new Guna.UI2.WinForms.Guna2Button();
            this.txt_admin = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_save = new Guna.UI2.WinForms.Guna2Button();
            this.txt_itemid = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_itemid2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SupplierData = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.guna2Elipse2 = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.guna2DragControl1 = new Guna.UI2.WinForms.Guna2DragControl(this.components);
            this.bunifuPanel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.SupplierData)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel3
            // 
            this.bunifuPanel3.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel3.BackgroundImage")));
            this.bunifuPanel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel3.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel3.BorderRadius = 20;
            this.bunifuPanel3.BorderThickness = 1;
            this.bunifuPanel3.Controls.Add(this.bunifuLabel10);
            this.bunifuPanel3.Controls.Add(this.txtnic);
            this.bunifuPanel3.Controls.Add(this.bunifuLabel8);
            this.bunifuPanel3.Controls.Add(this.txt_member);
            this.bunifuPanel3.Controls.Add(this.guna2ControlBox2);
            this.bunifuPanel3.Controls.Add(this.bunifuLabel7);
            this.bunifuPanel3.Controls.Add(this.bunifuLabel6);
            this.bunifuPanel3.Controls.Add(this.txt_address);
            this.bunifuPanel3.Controls.Add(this.bunifuLabel5);
            this.bunifuPanel3.Controls.Add(this.txt_cn);
            this.bunifuPanel3.Controls.Add(this.bunifuLabel4);
            this.bunifuPanel3.Controls.Add(this.txt_ma);
            this.bunifuPanel3.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel3.Controls.Add(this.guna2ControlBox1);
            this.bunifuPanel3.Controls.Add(this.btn_clear);
            this.bunifuPanel3.Controls.Add(this.label7);
            this.bunifuPanel3.Controls.Add(this.txt_sr);
            this.bunifuPanel3.Controls.Add(this.txt_memberid);
            this.bunifuPanel3.Controls.Add(this.btn_delete);
            this.bunifuPanel3.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel3.Controls.Add(this.btn_update);
            this.bunifuPanel3.Controls.Add(this.txt_admin);
            this.bunifuPanel3.Controls.Add(this.btn_save);
            this.bunifuPanel3.Controls.Add(this.txt_itemid);
            this.bunifuPanel3.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel3.Controls.Add(this.txt_itemid2);
            this.bunifuPanel3.Controls.Add(this.SupplierData);
            this.bunifuPanel3.Location = new System.Drawing.Point(16, 12);
            this.bunifuPanel3.Name = "bunifuPanel3";
            this.bunifuPanel3.ShowBorders = true;
            this.bunifuPanel3.Size = new System.Drawing.Size(1123, 711);
            this.bunifuPanel3.TabIndex = 116;
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.bunifuLabel10.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel10.Location = new System.Drawing.Point(43, 312);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(96, 16);
            this.bunifuLabel10.TabIndex = 150;
            this.bunifuLabel10.Text = "Contact Number";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtnic
            // 
            this.txtnic.AcceptsReturn = false;
            this.txtnic.AcceptsTab = false;
            this.txtnic.AnimationSpeed = 200;
            this.txtnic.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtnic.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtnic.AutoSizeHeight = true;
            this.txtnic.BackColor = System.Drawing.Color.Transparent;
            this.txtnic.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtnic.BackgroundImage")));
            this.txtnic.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtnic.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtnic.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtnic.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtnic.BorderRadius = 10;
            this.txtnic.BorderThickness = 1;
            this.txtnic.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Upper;
            this.txtnic.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtnic.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnic.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F);
            this.txtnic.DefaultText = "";
            this.txtnic.FillColor = System.Drawing.Color.White;
            this.txtnic.HideSelection = true;
            this.txtnic.IconLeft = null;
            this.txtnic.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnic.IconPadding = 10;
            this.txtnic.IconRight = null;
            this.txtnic.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnic.Lines = new string[0];
            this.txtnic.Location = new System.Drawing.Point(449, 74);
            this.txtnic.MaxLength = 32767;
            this.txtnic.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtnic.Modified = false;
            this.txtnic.Multiline = false;
            this.txtnic.Name = "txtnic";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnic.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtnic.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnic.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnic.OnIdleState = stateProperties4;
            this.txtnic.Padding = new System.Windows.Forms.Padding(3);
            this.txtnic.PasswordChar = '\0';
            this.txtnic.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtnic.PlaceholderText = "";
            this.txtnic.ReadOnly = false;
            this.txtnic.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtnic.SelectedText = "";
            this.txtnic.SelectionLength = 0;
            this.txtnic.SelectionStart = 0;
            this.txtnic.ShortcutsEnabled = true;
            this.txtnic.Size = new System.Drawing.Size(331, 38);
            this.txtnic.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtnic.TabIndex = 148;
            this.txtnic.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtnic.TextMarginBottom = 0;
            this.txtnic.TextMarginLeft = 0;
            this.txtnic.TextMarginTop = 0;
            this.txtnic.TextPlaceholder = "";
            this.txtnic.UseSystemPasswordChar = false;
            this.txtnic.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.bunifuLabel8.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel8.Location = new System.Drawing.Point(43, 183);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(50, 16);
            this.bunifuLabel8.TabIndex = 147;
            this.bunifuLabel8.Text = "Member ";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_member
            // 
            this.txt_member.AcceptsReturn = false;
            this.txt_member.AcceptsTab = false;
            this.txt_member.AnimationSpeed = 200;
            this.txt_member.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_member.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_member.AutoSizeHeight = true;
            this.txt_member.BackColor = System.Drawing.Color.Transparent;
            this.txt_member.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_member.BackgroundImage")));
            this.txt_member.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_member.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_member.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_member.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_member.BorderRadius = 10;
            this.txt_member.BorderThickness = 1;
            this.txt_member.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Upper;
            this.txt_member.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txt_member.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_member.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F);
            this.txt_member.DefaultText = "";
            this.txt_member.FillColor = System.Drawing.Color.White;
            this.txt_member.HideSelection = true;
            this.txt_member.IconLeft = null;
            this.txt_member.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_member.IconPadding = 10;
            this.txt_member.IconRight = null;
            this.txt_member.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_member.Lines = new string[0];
            this.txt_member.Location = new System.Drawing.Point(43, 205);
            this.txt_member.MaxLength = 32767;
            this.txt_member.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_member.Modified = false;
            this.txt_member.Multiline = false;
            this.txt_member.Name = "txt_member";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_member.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_member.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_member.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_member.OnIdleState = stateProperties8;
            this.txt_member.Padding = new System.Windows.Forms.Padding(3);
            this.txt_member.PasswordChar = '\0';
            this.txt_member.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_member.PlaceholderText = "";
            this.txt_member.ReadOnly = false;
            this.txt_member.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_member.SelectedText = "";
            this.txt_member.SelectionLength = 0;
            this.txt_member.SelectionStart = 0;
            this.txt_member.ShortcutsEnabled = true;
            this.txt_member.Size = new System.Drawing.Size(331, 38);
            this.txt_member.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_member.TabIndex = 146;
            this.txt_member.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_member.TextMarginBottom = 0;
            this.txt_member.TextMarginLeft = 0;
            this.txt_member.TextMarginTop = 0;
            this.txt_member.TextPlaceholder = "";
            this.txt_member.UseSystemPasswordChar = false;
            this.txt_member.WordWrap = true;
            // 
            // guna2ControlBox2
            // 
            this.guna2ControlBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.guna2ControlBox2.BackColor = System.Drawing.Color.Transparent;
            this.guna2ControlBox2.ControlBoxType = Guna.UI2.WinForms.Enums.ControlBoxType.MinimizeBox;
            this.guna2ControlBox2.FillColor = System.Drawing.Color.Transparent;
            this.guna2ControlBox2.HoverState.Parent = this.guna2ControlBox2;
            this.guna2ControlBox2.IconColor = System.Drawing.Color.Red;
            this.guna2ControlBox2.Location = new System.Drawing.Point(1051, 0);
            this.guna2ControlBox2.Name = "guna2ControlBox2";
            this.guna2ControlBox2.ShadowDecoration.Parent = this.guna2ControlBox2;
            this.guna2ControlBox2.Size = new System.Drawing.Size(33, 29);
            this.guna2ControlBox2.TabIndex = 145;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.bunifuLabel7.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel7.Location = new System.Drawing.Point(236, 6);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(129, 16);
            this.bunifuLabel7.TabIndex = 135;
            this.bunifuLabel7.Text = "Member Associate ID";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.bunifuLabel6.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel6.Location = new System.Drawing.Point(450, 120);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(51, 16);
            this.bunifuLabel6.TabIndex = 134;
            this.bunifuLabel6.Text = "Address";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_address
            // 
            this.txt_address.AcceptsReturn = false;
            this.txt_address.AcceptsTab = false;
            this.txt_address.AnimationSpeed = 200;
            this.txt_address.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_address.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_address.AutoSizeHeight = true;
            this.txt_address.BackColor = System.Drawing.Color.Transparent;
            this.txt_address.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_address.BackgroundImage")));
            this.txt_address.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_address.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_address.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_address.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_address.BorderRadius = 10;
            this.txt_address.BorderThickness = 1;
            this.txt_address.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_address.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_address.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_address.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F);
            this.txt_address.DefaultText = "";
            this.txt_address.FillColor = System.Drawing.Color.White;
            this.txt_address.HideSelection = true;
            this.txt_address.IconLeft = null;
            this.txt_address.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_address.IconPadding = 10;
            this.txt_address.IconRight = null;
            this.txt_address.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_address.Lines = new string[0];
            this.txt_address.Location = new System.Drawing.Point(449, 141);
            this.txt_address.MaxLength = 32767;
            this.txt_address.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_address.Modified = false;
            this.txt_address.Multiline = true;
            this.txt_address.Name = "txt_address";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_address.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_address.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_address.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_address.OnIdleState = stateProperties12;
            this.txt_address.Padding = new System.Windows.Forms.Padding(3);
            this.txt_address.PasswordChar = '\0';
            this.txt_address.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_address.PlaceholderText = "";
            this.txt_address.ReadOnly = false;
            this.txt_address.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_address.SelectedText = "";
            this.txt_address.SelectionLength = 0;
            this.txt_address.SelectionStart = 0;
            this.txt_address.ShortcutsEnabled = true;
            this.txt_address.Size = new System.Drawing.Size(331, 102);
            this.txt_address.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_address.TabIndex = 133;
            this.txt_address.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_address.TextMarginBottom = 0;
            this.txt_address.TextMarginLeft = 0;
            this.txt_address.TextMarginTop = 0;
            this.txt_address.TextPlaceholder = "";
            this.txt_address.UseSystemPasswordChar = false;
            this.txt_address.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.bunifuLabel5.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel5.Location = new System.Drawing.Point(450, 52);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(73, 16);
            this.bunifuLabel5.TabIndex = 132;
            this.bunifuLabel5.Text = "NIC Number";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_cn
            // 
            this.txt_cn.AcceptsReturn = false;
            this.txt_cn.AcceptsTab = false;
            this.txt_cn.AnimationSpeed = 200;
            this.txt_cn.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_cn.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_cn.AutoSizeHeight = true;
            this.txt_cn.BackColor = System.Drawing.Color.Transparent;
            this.txt_cn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_cn.BackgroundImage")));
            this.txt_cn.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_cn.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_cn.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_cn.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_cn.BorderRadius = 10;
            this.txt_cn.BorderThickness = 1;
            this.txt_cn.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Upper;
            this.txt_cn.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txt_cn.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_cn.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F);
            this.txt_cn.DefaultText = "";
            this.txt_cn.FillColor = System.Drawing.Color.White;
            this.txt_cn.HideSelection = true;
            this.txt_cn.IconLeft = null;
            this.txt_cn.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_cn.IconPadding = 10;
            this.txt_cn.IconRight = null;
            this.txt_cn.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_cn.Lines = new string[0];
            this.txt_cn.Location = new System.Drawing.Point(43, 334);
            this.txt_cn.MaxLength = 32767;
            this.txt_cn.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_cn.Modified = false;
            this.txt_cn.Multiline = false;
            this.txt_cn.Name = "txt_cn";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_cn.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_cn.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_cn.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_cn.OnIdleState = stateProperties16;
            this.txt_cn.Padding = new System.Windows.Forms.Padding(3);
            this.txt_cn.PasswordChar = '\0';
            this.txt_cn.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_cn.PlaceholderText = "";
            this.txt_cn.ReadOnly = false;
            this.txt_cn.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_cn.SelectedText = "";
            this.txt_cn.SelectionLength = 0;
            this.txt_cn.SelectionStart = 0;
            this.txt_cn.ShortcutsEnabled = true;
            this.txt_cn.Size = new System.Drawing.Size(331, 38);
            this.txt_cn.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_cn.TabIndex = 131;
            this.txt_cn.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_cn.TextMarginBottom = 0;
            this.txt_cn.TextMarginLeft = 0;
            this.txt_cn.TextMarginTop = 0;
            this.txt_cn.TextPlaceholder = "";
            this.txt_cn.UseSystemPasswordChar = false;
            this.txt_cn.WordWrap = true;
            this.txt_cn.TextChanged += new System.EventHandler(this.Txt_nic_TextChanged);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.bunifuLabel4.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel4.Location = new System.Drawing.Point(43, 248);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(113, 16);
            this.bunifuLabel4.TabIndex = 130;
            this.bunifuLabel4.Text = "Member Associate";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_ma
            // 
            this.txt_ma.AcceptsReturn = false;
            this.txt_ma.AcceptsTab = false;
            this.txt_ma.AnimationSpeed = 200;
            this.txt_ma.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_ma.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_ma.AutoSizeHeight = true;
            this.txt_ma.BackColor = System.Drawing.Color.Transparent;
            this.txt_ma.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_ma.BackgroundImage")));
            this.txt_ma.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_ma.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_ma.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_ma.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_ma.BorderRadius = 10;
            this.txt_ma.BorderThickness = 1;
            this.txt_ma.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_ma.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_ma.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ma.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F);
            this.txt_ma.DefaultText = "";
            this.txt_ma.FillColor = System.Drawing.Color.White;
            this.txt_ma.HideSelection = true;
            this.txt_ma.IconLeft = null;
            this.txt_ma.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ma.IconPadding = 10;
            this.txt_ma.IconRight = null;
            this.txt_ma.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ma.Lines = new string[0];
            this.txt_ma.Location = new System.Drawing.Point(43, 270);
            this.txt_ma.MaxLength = 32767;
            this.txt_ma.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_ma.Modified = false;
            this.txt_ma.Multiline = false;
            this.txt_ma.Name = "txt_ma";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ma.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_ma.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ma.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ma.OnIdleState = stateProperties20;
            this.txt_ma.Padding = new System.Windows.Forms.Padding(3);
            this.txt_ma.PasswordChar = '\0';
            this.txt_ma.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_ma.PlaceholderText = "";
            this.txt_ma.ReadOnly = false;
            this.txt_ma.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_ma.SelectedText = "";
            this.txt_ma.SelectionLength = 0;
            this.txt_ma.SelectionStart = 0;
            this.txt_ma.ShortcutsEnabled = true;
            this.txt_ma.Size = new System.Drawing.Size(331, 38);
            this.txt_ma.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_ma.TabIndex = 129;
            this.txt_ma.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_ma.TextMarginBottom = 0;
            this.txt_ma.TextMarginLeft = 0;
            this.txt_ma.TextMarginTop = 0;
            this.txt_ma.TextPlaceholder = "";
            this.txt_ma.UseSystemPasswordChar = false;
            this.txt_ma.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel3.Location = new System.Drawing.Point(450, 249);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(104, 16);
            this.bunifuLabel3.TabIndex = 128;
            this.bunifuLabel3.Text = "Special Remarks";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // guna2ControlBox1
            // 
            this.guna2ControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.guna2ControlBox1.BackColor = System.Drawing.Color.Transparent;
            this.guna2ControlBox1.FillColor = System.Drawing.Color.Transparent;
            this.guna2ControlBox1.HoverState.Parent = this.guna2ControlBox1;
            this.guna2ControlBox1.IconColor = System.Drawing.Color.Red;
            this.guna2ControlBox1.Location = new System.Drawing.Point(1090, -1);
            this.guna2ControlBox1.Name = "guna2ControlBox1";
            this.guna2ControlBox1.ShadowDecoration.Parent = this.guna2ControlBox1;
            this.guna2ControlBox1.Size = new System.Drawing.Size(33, 29);
            this.guna2ControlBox1.TabIndex = 51;
            this.guna2ControlBox1.Click += new System.EventHandler(this.Guna2ControlBox1_Click);
            // 
            // btn_clear
            // 
            this.btn_clear.Animated = true;
            this.btn_clear.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_clear.BorderRadius = 5;
            this.btn_clear.BorderThickness = 1;
            this.btn_clear.CheckedState.Parent = this.btn_clear;
            this.btn_clear.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btn_clear.CustomImages.Parent = this.btn_clear;
            this.btn_clear.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(51)))), ((int)(((byte)(150)))));
            this.btn_clear.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.btn_clear.ForeColor = System.Drawing.Color.White;
            this.btn_clear.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(178)))));
            this.btn_clear.HoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(66)))), ((int)(((byte)(235)))));
            this.btn_clear.HoverState.Parent = this.btn_clear;
            this.btn_clear.Location = new System.Drawing.Point(861, 277);
            this.btn_clear.Name = "btn_clear";
            this.btn_clear.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(178)))));
            this.btn_clear.ShadowDecoration.Parent = this.btn_clear;
            this.btn_clear.Size = new System.Drawing.Size(206, 38);
            this.btn_clear.TabIndex = 127;
            this.btn_clear.Text = "Clear";
            this.btn_clear.Click += new System.EventHandler(this.btn_clear_Click);
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.White;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label7.Location = new System.Drawing.Point(0, 3);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(168, 16);
            this.label7.TabIndex = 122;
            this.label7.Text = "Add Member Associate";
            // 
            // txt_sr
            // 
            this.txt_sr.AcceptsReturn = false;
            this.txt_sr.AcceptsTab = false;
            this.txt_sr.AnimationSpeed = 200;
            this.txt_sr.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_sr.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_sr.AutoSizeHeight = true;
            this.txt_sr.BackColor = System.Drawing.Color.Transparent;
            this.txt_sr.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_sr.BackgroundImage")));
            this.txt_sr.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_sr.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_sr.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_sr.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_sr.BorderRadius = 10;
            this.txt_sr.BorderThickness = 1;
            this.txt_sr.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_sr.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_sr.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_sr.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F);
            this.txt_sr.DefaultText = "";
            this.txt_sr.FillColor = System.Drawing.Color.White;
            this.txt_sr.HideSelection = true;
            this.txt_sr.IconLeft = null;
            this.txt_sr.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_sr.IconPadding = 10;
            this.txt_sr.IconRight = null;
            this.txt_sr.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_sr.Lines = new string[0];
            this.txt_sr.Location = new System.Drawing.Point(449, 270);
            this.txt_sr.MaxLength = 32767;
            this.txt_sr.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_sr.Modified = false;
            this.txt_sr.Multiline = true;
            this.txt_sr.Name = "txt_sr";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_sr.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_sr.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_sr.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_sr.OnIdleState = stateProperties24;
            this.txt_sr.Padding = new System.Windows.Forms.Padding(3);
            this.txt_sr.PasswordChar = '\0';
            this.txt_sr.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_sr.PlaceholderText = "";
            this.txt_sr.ReadOnly = false;
            this.txt_sr.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_sr.SelectedText = "";
            this.txt_sr.SelectionLength = 0;
            this.txt_sr.SelectionStart = 0;
            this.txt_sr.ShortcutsEnabled = true;
            this.txt_sr.Size = new System.Drawing.Size(331, 102);
            this.txt_sr.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_sr.TabIndex = 126;
            this.txt_sr.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_sr.TextMarginBottom = 0;
            this.txt_sr.TextMarginLeft = 0;
            this.txt_sr.TextMarginTop = 0;
            this.txt_sr.TextPlaceholder = "";
            this.txt_sr.UseSystemPasswordChar = false;
            this.txt_sr.WordWrap = true;
            // 
            // txt_memberid
            // 
            this.txt_memberid.AcceptsReturn = false;
            this.txt_memberid.AcceptsTab = false;
            this.txt_memberid.AnimationSpeed = 200;
            this.txt_memberid.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.txt_memberid.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.txt_memberid.AutoSizeHeight = true;
            this.txt_memberid.BackColor = System.Drawing.Color.Transparent;
            this.txt_memberid.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_memberid.BackgroundImage")));
            this.txt_memberid.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_memberid.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_memberid.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_memberid.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_memberid.BorderRadius = 10;
            this.txt_memberid.BorderThickness = 1;
            this.txt_memberid.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_memberid.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_memberid.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_memberid.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F);
            this.txt_memberid.DefaultText = "";
            this.txt_memberid.FillColor = System.Drawing.Color.White;
            this.txt_memberid.HideSelection = true;
            this.txt_memberid.IconLeft = null;
            this.txt_memberid.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_memberid.IconPadding = 10;
            this.txt_memberid.IconRight = null;
            this.txt_memberid.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_memberid.Lines = new string[0];
            this.txt_memberid.Location = new System.Drawing.Point(43, 74);
            this.txt_memberid.MaxLength = 32767;
            this.txt_memberid.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_memberid.Modified = false;
            this.txt_memberid.Multiline = false;
            this.txt_memberid.Name = "txt_memberid";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_memberid.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_memberid.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_memberid.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_memberid.OnIdleState = stateProperties28;
            this.txt_memberid.Padding = new System.Windows.Forms.Padding(3);
            this.txt_memberid.PasswordChar = '\0';
            this.txt_memberid.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_memberid.PlaceholderText = "";
            this.txt_memberid.ReadOnly = false;
            this.txt_memberid.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_memberid.SelectedText = "";
            this.txt_memberid.SelectionLength = 0;
            this.txt_memberid.SelectionStart = 0;
            this.txt_memberid.ShortcutsEnabled = true;
            this.txt_memberid.Size = new System.Drawing.Size(331, 38);
            this.txt_memberid.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_memberid.TabIndex = 116;
            this.txt_memberid.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_memberid.TextMarginBottom = 0;
            this.txt_memberid.TextMarginLeft = 0;
            this.txt_memberid.TextMarginTop = 0;
            this.txt_memberid.TextPlaceholder = "";
            this.txt_memberid.UseSystemPasswordChar = false;
            this.txt_memberid.WordWrap = true;
            this.txt_memberid.TextChanged += new System.EventHandler(this.Txt_memberid_TextChanged);
            // 
            // btn_delete
            // 
            this.btn_delete.Animated = true;
            this.btn_delete.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_delete.BorderRadius = 5;
            this.btn_delete.BorderThickness = 1;
            this.btn_delete.CheckedState.Parent = this.btn_delete;
            this.btn_delete.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btn_delete.CustomImages.Parent = this.btn_delete;
            this.btn_delete.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(51)))), ((int)(((byte)(150)))));
            this.btn_delete.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.btn_delete.ForeColor = System.Drawing.Color.White;
            this.btn_delete.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(178)))));
            this.btn_delete.HoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(66)))), ((int)(((byte)(235)))));
            this.btn_delete.HoverState.Parent = this.btn_delete;
            this.btn_delete.Location = new System.Drawing.Point(861, 224);
            this.btn_delete.Name = "btn_delete";
            this.btn_delete.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(178)))));
            this.btn_delete.ShadowDecoration.Parent = this.btn_delete;
            this.btn_delete.Size = new System.Drawing.Size(206, 38);
            this.btn_delete.TabIndex = 125;
            this.btn_delete.Text = "Delete";
            this.btn_delete.Click += new System.EventHandler(this.btn_delete_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel2.Location = new System.Drawing.Point(43, 119);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(38, 16);
            this.bunifuLabel2.TabIndex = 118;
            this.bunifuLabel2.Text = "Admin ";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btn_update
            // 
            this.btn_update.Animated = true;
            this.btn_update.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_update.BorderRadius = 5;
            this.btn_update.BorderThickness = 1;
            this.btn_update.CheckedState.Parent = this.btn_update;
            this.btn_update.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btn_update.CustomImages.Parent = this.btn_update;
            this.btn_update.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(51)))), ((int)(((byte)(150)))));
            this.btn_update.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.btn_update.ForeColor = System.Drawing.Color.White;
            this.btn_update.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(178)))));
            this.btn_update.HoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(66)))), ((int)(((byte)(235)))));
            this.btn_update.HoverState.Parent = this.btn_update;
            this.btn_update.Location = new System.Drawing.Point(861, 171);
            this.btn_update.Name = "btn_update";
            this.btn_update.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(178)))));
            this.btn_update.ShadowDecoration.Parent = this.btn_update;
            this.btn_update.Size = new System.Drawing.Size(206, 38);
            this.btn_update.TabIndex = 124;
            this.btn_update.Text = "Update";
            this.btn_update.Click += new System.EventHandler(this.btn_update_Click);
            // 
            // txt_admin
            // 
            this.txt_admin.AcceptsReturn = false;
            this.txt_admin.AcceptsTab = false;
            this.txt_admin.AnimationSpeed = 200;
            this.txt_admin.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.txt_admin.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.txt_admin.AutoSizeHeight = true;
            this.txt_admin.BackColor = System.Drawing.Color.Transparent;
            this.txt_admin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_admin.BackgroundImage")));
            this.txt_admin.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_admin.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_admin.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_admin.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_admin.BorderRadius = 10;
            this.txt_admin.BorderThickness = 1;
            this.txt_admin.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Upper;
            this.txt_admin.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txt_admin.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_admin.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F);
            this.txt_admin.DefaultText = "";
            this.txt_admin.FillColor = System.Drawing.Color.White;
            this.txt_admin.HideSelection = true;
            this.txt_admin.IconLeft = null;
            this.txt_admin.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_admin.IconPadding = 10;
            this.txt_admin.IconRight = null;
            this.txt_admin.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_admin.Lines = new string[0];
            this.txt_admin.Location = new System.Drawing.Point(43, 141);
            this.txt_admin.MaxLength = 32767;
            this.txt_admin.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_admin.Modified = false;
            this.txt_admin.Multiline = false;
            this.txt_admin.Name = "txt_admin";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_admin.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_admin.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_admin.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_admin.OnIdleState = stateProperties32;
            this.txt_admin.Padding = new System.Windows.Forms.Padding(3);
            this.txt_admin.PasswordChar = '\0';
            this.txt_admin.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_admin.PlaceholderText = "";
            this.txt_admin.ReadOnly = false;
            this.txt_admin.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_admin.SelectedText = "";
            this.txt_admin.SelectionLength = 0;
            this.txt_admin.SelectionStart = 0;
            this.txt_admin.ShortcutsEnabled = true;
            this.txt_admin.Size = new System.Drawing.Size(331, 38);
            this.txt_admin.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_admin.TabIndex = 115;
            this.txt_admin.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_admin.TextMarginBottom = 0;
            this.txt_admin.TextMarginLeft = 0;
            this.txt_admin.TextMarginTop = 0;
            this.txt_admin.TextPlaceholder = "";
            this.txt_admin.UseSystemPasswordChar = false;
            this.txt_admin.WordWrap = true;
            // 
            // btn_save
            // 
            this.btn_save.Animated = true;
            this.btn_save.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_save.BorderRadius = 5;
            this.btn_save.BorderThickness = 1;
            this.btn_save.CheckedState.Parent = this.btn_save;
            this.btn_save.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btn_save.CustomImages.Parent = this.btn_save;
            this.btn_save.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(51)))), ((int)(((byte)(150)))));
            this.btn_save.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.btn_save.ForeColor = System.Drawing.Color.White;
            this.btn_save.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(178)))));
            this.btn_save.HoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(66)))), ((int)(((byte)(235)))));
            this.btn_save.HoverState.Parent = this.btn_save;
            this.btn_save.Location = new System.Drawing.Point(861, 117);
            this.btn_save.Name = "btn_save";
            this.btn_save.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(178)))));
            this.btn_save.ShadowDecoration.Parent = this.btn_save;
            this.btn_save.Size = new System.Drawing.Size(206, 38);
            this.btn_save.TabIndex = 123;
            this.btn_save.Text = "Save";
            this.btn_save.Click += new System.EventHandler(this.Btn_save_Click);
            // 
            // txt_itemid
            // 
            this.txt_itemid.AcceptsReturn = false;
            this.txt_itemid.AcceptsTab = false;
            this.txt_itemid.AnimationSpeed = 200;
            this.txt_itemid.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_itemid.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_itemid.AutoSizeHeight = true;
            this.txt_itemid.BackColor = System.Drawing.Color.Transparent;
            this.txt_itemid.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_itemid.BackgroundImage")));
            this.txt_itemid.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_itemid.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_itemid.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_itemid.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_itemid.BorderRadius = 10;
            this.txt_itemid.BorderThickness = 1;
            this.txt_itemid.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Upper;
            this.txt_itemid.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txt_itemid.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_itemid.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F);
            this.txt_itemid.DefaultText = "";
            this.txt_itemid.FillColor = System.Drawing.Color.White;
            this.txt_itemid.HideSelection = true;
            this.txt_itemid.IconLeft = null;
            this.txt_itemid.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_itemid.IconPadding = 10;
            this.txt_itemid.IconRight = null;
            this.txt_itemid.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_itemid.Lines = new string[0];
            this.txt_itemid.Location = new System.Drawing.Point(371, 1);
            this.txt_itemid.MaxLength = 32767;
            this.txt_itemid.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_itemid.Modified = false;
            this.txt_itemid.Multiline = false;
            this.txt_itemid.Name = "txt_itemid";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_itemid.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_itemid.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_itemid.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_itemid.OnIdleState = stateProperties36;
            this.txt_itemid.Padding = new System.Windows.Forms.Padding(3);
            this.txt_itemid.PasswordChar = '\0';
            this.txt_itemid.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_itemid.PlaceholderText = "";
            this.txt_itemid.ReadOnly = true;
            this.txt_itemid.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_itemid.SelectedText = "";
            this.txt_itemid.SelectionLength = 0;
            this.txt_itemid.SelectionStart = 0;
            this.txt_itemid.ShortcutsEnabled = true;
            this.txt_itemid.Size = new System.Drawing.Size(106, 27);
            this.txt_itemid.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_itemid.TabIndex = 120;
            this.txt_itemid.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_itemid.TextMarginBottom = 0;
            this.txt_itemid.TextMarginLeft = 0;
            this.txt_itemid.TextMarginTop = 0;
            this.txt_itemid.TextPlaceholder = "";
            this.txt_itemid.UseSystemPasswordChar = false;
            this.txt_itemid.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel1.Location = new System.Drawing.Point(43, 52);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(66, 16);
            this.bunifuLabel1.TabIndex = 117;
            this.bunifuLabel1.Text = "Member ID";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_itemid2
            // 
            this.txt_itemid2.AcceptsReturn = false;
            this.txt_itemid2.AcceptsTab = false;
            this.txt_itemid2.AnimationSpeed = 200;
            this.txt_itemid2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_itemid2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_itemid2.AutoSizeHeight = true;
            this.txt_itemid2.BackColor = System.Drawing.Color.Transparent;
            this.txt_itemid2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_itemid2.BackgroundImage")));
            this.txt_itemid2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_itemid2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_itemid2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_itemid2.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_itemid2.BorderRadius = 10;
            this.txt_itemid2.BorderThickness = 1;
            this.txt_itemid2.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Upper;
            this.txt_itemid2.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txt_itemid2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_itemid2.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F);
            this.txt_itemid2.DefaultText = "";
            this.txt_itemid2.FillColor = System.Drawing.Color.White;
            this.txt_itemid2.HideSelection = true;
            this.txt_itemid2.IconLeft = null;
            this.txt_itemid2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_itemid2.IconPadding = 10;
            this.txt_itemid2.IconRight = null;
            this.txt_itemid2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_itemid2.Lines = new string[0];
            this.txt_itemid2.Location = new System.Drawing.Point(742, 1);
            this.txt_itemid2.MaxLength = 32767;
            this.txt_itemid2.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_itemid2.Modified = false;
            this.txt_itemid2.Multiline = false;
            this.txt_itemid2.Name = "txt_itemid2";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_itemid2.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_itemid2.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_itemid2.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_itemid2.OnIdleState = stateProperties40;
            this.txt_itemid2.Padding = new System.Windows.Forms.Padding(3);
            this.txt_itemid2.PasswordChar = '\0';
            this.txt_itemid2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_itemid2.PlaceholderText = "";
            this.txt_itemid2.ReadOnly = true;
            this.txt_itemid2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_itemid2.SelectedText = "";
            this.txt_itemid2.SelectionLength = 0;
            this.txt_itemid2.SelectionStart = 0;
            this.txt_itemid2.ShortcutsEnabled = true;
            this.txt_itemid2.Size = new System.Drawing.Size(106, 27);
            this.txt_itemid2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_itemid2.TabIndex = 121;
            this.txt_itemid2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_itemid2.TextMarginBottom = 0;
            this.txt_itemid2.TextMarginLeft = 0;
            this.txt_itemid2.TextMarginTop = 0;
            this.txt_itemid2.TextPlaceholder = "";
            this.txt_itemid2.UseSystemPasswordChar = false;
            this.txt_itemid2.Visible = false;
            this.txt_itemid2.WordWrap = true;
            // 
            // SupplierData
            // 
            this.SupplierData.AllowCustomTheming = true;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.SupplierData.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.SupplierData.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.SupplierData.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.SupplierData.BackgroundColor = System.Drawing.Color.White;
            this.SupplierData.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.SupplierData.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this.SupplierData.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(122)))), ((int)(((byte)(224)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.SupplierData.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.SupplierData.ColumnHeadersHeight = 50;
            this.SupplierData.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.SupplierData.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.White;
            this.SupplierData.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.SupplierData.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.SupplierData.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.SystemColors.ControlDark;
            this.SupplierData.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.SupplierData.CurrentTheme.BackColor = System.Drawing.Color.LightSteelBlue;
            this.SupplierData.CurrentTheme.GridColor = System.Drawing.Color.White;
            this.SupplierData.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(122)))), ((int)(((byte)(224)))));
            this.SupplierData.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SupplierData.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.SupplierData.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.SupplierData.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.SupplierData.CurrentTheme.Name = null;
            this.SupplierData.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.SupplierData.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.SupplierData.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.SupplierData.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(226)))), ((int)(((byte)(244)))));
            this.SupplierData.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(226)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.SupplierData.DefaultCellStyle = dataGridViewCellStyle3;
            this.SupplierData.EnableHeadersVisualStyles = false;
            this.SupplierData.GridColor = System.Drawing.Color.White;
            this.SupplierData.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(122)))), ((int)(((byte)(224)))));
            this.SupplierData.HeaderBgColor = System.Drawing.Color.Empty;
            this.SupplierData.HeaderForeColor = System.Drawing.Color.White;
            this.SupplierData.Location = new System.Drawing.Point(0, 397);
            this.SupplierData.Name = "SupplierData";
            this.SupplierData.ReadOnly = true;
            this.SupplierData.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.SupplierData.RowHeadersVisible = false;
            this.SupplierData.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.AutoSizeToAllHeaders;
            this.SupplierData.RowTemplate.Height = 40;
            this.SupplierData.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.SupplierData.Size = new System.Drawing.Size(1120, 311);
            this.SupplierData.StandardTab = true;
            this.SupplierData.TabIndex = 119;
            this.SupplierData.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.DarkViolet;
            this.SupplierData.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.SupplierData_CellContentClick);
            // 
            // guna2Elipse2
            // 
            this.guna2Elipse2.BorderRadius = 20;
            this.guna2Elipse2.TargetControl = this;
            // 
            // guna2DragControl1
            // 
            this.guna2DragControl1.TargetControl = null;
            // 
            // Add_Member_Associate
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1151, 735);
            this.Controls.Add(this.bunifuPanel3);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Add_Member_Associate";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Add_Member_Associate";
            this.Load += new System.EventHandler(this.Add_Member_Associate_Load);
            this.bunifuPanel3.ResumeLayout(false);
            this.bunifuPanel3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.SupplierData)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel3;
        private Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox txt_address;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox txt_cn;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox txt_ma;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox1;
        private Guna.UI2.WinForms.Guna2Button btn_clear;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox txt_sr;
        private Bunifu.UI.WinForms.BunifuTextBox txt_memberid;
        private Guna.UI2.WinForms.Guna2Button btn_delete;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Guna.UI2.WinForms.Guna2Button btn_update;
        private Bunifu.UI.WinForms.BunifuTextBox txt_admin;
        private Guna.UI2.WinForms.Guna2Button btn_save;
        private Bunifu.UI.WinForms.BunifuTextBox txt_itemid;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox txt_itemid2;
        private Bunifu.UI.WinForms.BunifuDataGridView SupplierData;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse2;
        private Guna.UI2.WinForms.Guna2DragControl guna2DragControl1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox txt_member;
        private Bunifu.UI.WinForms.BunifuTextBox txtnic;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
    }
}